stateDiagram-v2
    title TLS Context State Machine

    [*] --> Init: Context Creation
    
    state Init {
        [*] --> CheckConfig
        CheckConfig --> NoCerts: No Certificates\nConfigured
        CheckConfig --> WithCerts: Certificates\nConfigured
        
        state NoCerts {
            [*] --> CheckStopFlag
            CheckStopFlag --> Exit: stop_if_no_cert=true
            CheckStopFlag --> Continue: stop_if_no_cert=false
        }
    }

    Init --> DegradedMode: No Certs &\nstop_if_no_cert=false
    Init --> [*]: No Certs &\nstop_if_no_cert=true
    Init --> TcpReady: Certificates\nConfigured
    
    TcpReady --> TlsReady: Certificate\nStatus Valid
    TcpReady --> DegradedMode: Certificate\nStatus Invalid &\nstop_if_no_cert=false
    TcpReady --> [*]: Certificate\nStatus Invalid &\nstop_if_no_cert=true
    TcpReady --> Suspended: Certificate\nStatus Unknown &\nstop_if_no_cert=true
    TcpReady --> DegradedMode: Certificate\nStatus Unknown &\nstop_if_no_cert=false
    
    TlsReady --> TcpReady: Certificate\nStatus Unknown &\nstop_if_no_cert=false
    TlsReady --> Suspended: Certificate\nStatus Unknown &\nstop_if_no_cert=true
    TlsReady --> DegradedMode: Certificate\nStatus Invalid &\nstop_if_no_cert=false
    TlsReady --> [*]: Certificate\nStatus Invalid &\nstop_if_no_cert=true
    
    Suspended --> TlsReady: Certificate\nStatus Valid
    Suspended --> [*]: Certificate\nStatus Invalid
    
    DegradedMode --> TcpReady: Certificates\nConfigured
    
    state DegradedMode {
        [*] --> TCP_Only: stop_if_no_cert=false
    }
    
    state TcpReady {
        [*] --> Accept_TCP
        Accept_TCP --> Defer_TLS: TLS Request
    }
    
    state TlsReady {
        [*] --> Accept_All
    }
    
    state Suspended {
        [*] --> WaitingPVACMS
        WaitingPVACMS --> CheckStatus: PVACMS\nConnected
    } 