sequenceDiagram
    title PV Access TLS
    
    participant Client as PV Access Client
    participant Server as PV Access Server
    participant ServerB as PV Access Server B
    participant CA as Certificate Authority
    participant IOC as IOC

    Note left of Client: PV Access channel search
    Client->>Server: Search Request(protocol["tcp","tls"])
    Server-->>Client: Search Response (protocol: "tls", ipv6_address)
    ServerB-->>Client: Search Response (protocol: "tcp", ipv6_address)
    Client->>Client: Select Response
    Client->>Server: Establish tcp/ip connection
    Note over Client,Server: tcp/ip connection established
    
    Note left of Client: TLS Handshake
    Client->>+Server: TLS Client Hello record(PV Access Client_random, cipher[], compression[])
    Server-->>-Client: TLS Server Hello record(PV Access Server_random, session_id, cipher, compression, certificate)
    Client->>+CA: Verify(certificate)
    CA-->>-Client: Verified
    Client-->>+Server: pre-secret<encrypted with PV Access Server's public key>
    Client->>Client: Generate secret from pre-secret
    Server->>Server: Decrypt pre-secret using private key
    Server->>-Server: Generate secret from pre-secret
    
    Note over Client,Server: From here all PV Access messages are TLS encapsulated using TLS record state
    Note left of Client: PV Access channel negotiotion
    Server->>+Client: connection validation request
    Client-->>-Server: connection validation response
    
    Note left of Client: Data exchange
    loop PV Access Data exchange
        alt hello message
            Note left of Client: Server Certificate Replacement
            Server->>+Client: TLS Hello Message
            Client->>+Server: TLS Client Hello record(PV Access Client_random, cipher[], compression[])
            Server-->>-Client: TLS Server Hello record(PV Access Server_random, session_id, cipher, compression, certificate)
            Client->>+CA: Verify(certificate)
            CA-->>-Client: Verified
            Client-->>+Server: pre-secret<encrypted with PV Access Server's public key>
            Client->>Client: Generate secret from pre-secret
            Server->>Server: Decrypt pre-secret using private key
            Server->>-Server: Generate secret from pre-secret
            Note over Client,Server: From here TLS record state is changed
        else control message
            Client->>+Server: TLS record encalsulated<PV Access Control message>
            Server->>-Client: TLS record encalsulated<PV Access Control message>
        else application message
            Client->>+Server: TLS record encalsulated<PV Access Application message>
            Server->>+IOC: access PV
            IOC-->>-Server: response
            Server->>-Client: TLS record encapsulated<PV Access Application message>
        end
    end 