name: Docker Change Detection Pipeline

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Which image to build'
        required: true
        type: choice
        options:
          - epics-base
          - pvxs
          - spva_std
          - spva_krb
          - spva_ldap
          - all
  push:
    branches:
      - 'tls-dev'

jobs:
  check_docker_changes:
    runs-on: ubuntu-22.04
    outputs:
      non_docker_changed: ${{ steps.filter.outputs.non_docker }}
      spva_std_changed: ${{ steps.filter.outputs.spva_std }}
      spva_krb_changed: ${{ steps.filter.outputs.spva_krb }}
      spva_ldap_changed: ${{ steps.filter.outputs.spva_ldap }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ github.event.before }}
          filters: |
            non_docker:
              - '**'
              - '!example/**'
              - '!.github/**'
            spva_std:
              - 'example/docker/spva_std/**'
            spva_krb:
              - 'example/docker/spva_krb/**'
            spva_ldap:
              - 'example/docker/spva_ldap/**'

  build-epics-base:
    if: |
      github.event_name == 'workflow_dispatch' && 
      (github.event.inputs.build_target == 'epics-base' || github.event.inputs.build_target == 'all')
    uses: george-mcintyre/epics-base/.github/workflows/docker-pub-epics-base.yml@7.0-method_and_authority
    secrets:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  build-pvxs:
    needs: check_docker_changes
    if: |
      (github.event_name == 'workflow_dispatch' && 
       (github.event.inputs.build_target == 'pvxs' || github.event.inputs.build_target == 'all')) || 
      (github.event_name == 'push' && 
       needs.check_docker_changes.outputs.non_docker_changed == 'true')
    runs-on: ubuntu-22.04
    outputs:
      status: ${{ job.status }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: tls-dev
          submodules: recursive
      # Add your build steps here
      - name: Build pvxs
        run: echo "Building pvxs"

  build-spva-std:
    needs: check_docker_changes
    if: |
      (github.event_name == 'workflow_dispatch' && 
       (github.event.inputs.build_target == 'spva_std' || github.event.inputs.build_target == 'all')) || 
      (github.event_name == 'push' && 
       needs.check_docker_changes.outputs.spva_std_changed == 'true' && 
       needs.check_docker_changes.outputs.non_docker_changed == 'false')
    runs-on: ubuntu-22.04
    outputs:
      status: ${{ job.status }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: tls-dev
      # Add your build steps here
      - name: Build spva_std
        run: echo "Building spva_std"

  trigger-dependent-builds:
    needs: [check_docker_changes, build-pvxs, build-spva-std]
    if: |
      always() &&
      (needs.build-pvxs.result == 'success' || needs.check_docker_changes.outputs.spva_std_changed == 'true')
    runs-on: ubuntu-22.04
    steps:
      - name: Trigger dependent builds workflow
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.name,
              workflow_id: 'docker-builds.yml',
              ref: 'tls-dev',
              inputs: {
                pvxs_status: '${{ needs.build-pvxs.result }}',
                spva_std_status: '${{ needs.build-spva-std.result }}'
              }
            })